edc.ids.id=urn:connector:client-8
edc.participant.id=client-8
edc.dsp.callback.address=http://client-8-connector:22282/protocol
web.http.port=22181
web.http.path=/api
web.http.management.port=22182
web.http.management.path=/management
web.http.protocol.port=22282
web.http.protocol.path=/protocol
web.http.control.port=22283
web.http.control.path=/control
web.http.public.port=22284
web.http.public.path=/public
edc.api.auth.key=password
edc.ionos.nextcloud.endpoint=http://client-8-nextcloud:80
edc.ionos.nextcloud.username=padmin
edc.ionos.nextcloud.password=p123
edc.log.level=DEBUG
