edc.ids.id=urn:connector:client-10
edc.participant.id=client-10
edc.dsp.callback.address=http://client-10-connector:26282/protocol
web.http.port=26181
web.http.path=/api
web.http.management.port=26182
web.http.management.path=/management
web.http.protocol.port=26282
web.http.protocol.path=/protocol
web.http.control.port=26283
web.http.control.path=/control
web.http.public.port=26284
web.http.public.path=/public
edc.api.auth.key=password
edc.ionos.nextcloud.endpoint=http://client-10-nextcloud:80
edc.ionos.nextcloud.username=padmin
edc.ionos.nextcloud.password=p123
edc.log.level=DEBUG
