edc.ids.id=urn:connector:client-5
edc.participant.id=client-5
edc.dsp.callback.address=http://client-5-connector:16282/protocol
web.http.port=16181
web.http.path=/api
web.http.management.port=16182
web.http.management.path=/management
web.http.protocol.port=16282
web.http.protocol.path=/protocol
web.http.control.port=16283
web.http.control.path=/control
web.http.public.port=16284
web.http.public.path=/public
edc.api.auth.key=password
edc.ionos.nextcloud.endpoint=http://client-5-nextcloud:80
edc.ionos.nextcloud.username=padmin
edc.ionos.nextcloud.password=p123
edc.log.level=DEBUG
