edc.ids.id=urn:connector:client-6
edc.participant.id=client-6
edc.dsp.callback.address=http://client-6-connector:18282/protocol
web.http.port=18181
web.http.path=/api
web.http.management.port=18182
web.http.management.path=/management
web.http.protocol.port=18282
web.http.protocol.path=/protocol
web.http.control.port=18283
web.http.control.path=/control
web.http.public.port=18284
web.http.public.path=/public
edc.api.auth.key=password
edc.ionos.nextcloud.endpoint=http://client-6-nextcloud:80
edc.ionos.nextcloud.username=padmin
edc.ionos.nextcloud.password=p123
edc.log.level=DEBUG
