# NS-3 Network Simulator
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    python3 \
    python3-dev \
    libsqlite3-dev \
    libxml2-dev \
    libgsl-dev \
    netcat-openbsd \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /ns3

RUN mkdir -p /app/logs
COPY ns3-fl-network .

RUN python3 ./waf configure \
    --enable-examples \
    --disable-werror \
    --enable-modules=core,network,applications,bridge,csma,energy,flow-monitor,internet,mobility,point-to-point,propagation,spectrum,stats,traffic-control,wifi,reliability && \
    python3 ./waf build -j1

CMD ["bash", "-lc", "mkdir -p \"${LOGS_PATH}\" && cd /ns3 && python3 ./waf --run \"wifi_exp --NumClients=${NUM_CLIENTS} --Port=${NS3_PORT} --NetworkType=${NS3_NETWORK_TYPE} --LearningModel=${NS3_NETWORK_MODE} --MaxPacketSize=${NS3_PACKET_SIZE} --ModelSize=${NS3_MODEL_SIZE} --ClientDataRate=${NS3_CLIENT_DATA_RATE} --ServerDataRate=${NS3_SERVER_DATA_RATE}\""]





