edc.ids.id=urn:connector:research-centre
edc.participant.id=research-centre
edc.dsp.callback.address=http://research-centre-connector:9292/protocol
web.http.port=9191
web.http.path=/api
web.http.management.port=9192
web.http.management.path=/management
web.http.protocol.port=9292
web.http.protocol.path=/protocol
web.http.control.port=9293
web.http.control.path=/control
web.http.public.port=9294
web.http.public.path=/public
edc.api.auth.key=password
edc.ionos.nextcloud.endpoint=http://research-centre-nextcloud:80
edc.ionos.nextcloud.username=cadmin
edc.ionos.nextcloud.password=c123
edc.log.level=DEBUG
