edc.ids.id=urn:connector:client-7
edc.participant.id=client-7
edc.dsp.callback.address=http://client-7-connector:20282/protocol
web.http.port=20181
web.http.path=/api
web.http.management.port=20182
web.http.management.path=/management
web.http.protocol.port=20282
web.http.protocol.path=/protocol
web.http.control.port=20283
web.http.control.path=/control
web.http.public.port=20284
web.http.public.path=/public
edc.api.auth.key=password
edc.ionos.nextcloud.endpoint=http://client-7-nextcloud:80
edc.ionos.nextcloud.username=padmin
edc.ionos.nextcloud.password=p123
edc.log.level=DEBUG